### ISSUE TITLE
A question for the paper

### ISSUE THREAD

**Issue by waterhorse1** [FreedomIntelligence/OVM#1]
Dear authors,

Great work! I have one question about the paper. The paper mentions in the implementation section that "Given that GSM8K provides calculation annotations, our models were also trained to utilize calculators". So will you use the calculator during the inference process? If so why your algorithm does not belong to code-based solutions?

**Comment by OakYU** [comment]
Yes, we also utilize a calculator during inference. We describe the method that uses a code block, represents intermediate steps with code, and executes the code block to derive the final answer as code-based methods here. It is globally based on code. In contrast, we use the calculator locally for expression computation, while steps are still in natural language.

Thank you for your attention; we will clarify this matter in the next version.

**Comment by waterhorse1** [comment]
Get it, thanks.
