### ISSUE TITLE
Dataset release for the OVM training

### ISSUE THREAD

**Issue by hbin0701** [FreedomIntelligence/OVM#3]
Dear Authors,
thank you for the great work and the code! :)
The idea seems very simple but inspiring, along with the great performance - also love how the code is organized so neatly!

I've realized that however generating the train set for OVM, i.e. running `bash scripts/gsm8k/generate.sh`
would take about  8 x V100 130 hours. 😢 

It would be of great help if you could kindly release the dataset via Google Drive or Huggingface to replicate your work. 
Thank you 😄

**Comment by OakYU** [comment]
Thanks for your appreciation! We just released the generated data: https://huggingface.co/datasets/FreedomIntelligence/OVM-dataset

**Comment by hbin0701** [comment]
Thanks a lot!! :)
