### ISSUE TITLE
Compatibility with 13B model

### ISSUE THREAD

**Issue by hbin0701** [FreedomIntelligence/OVM#4]
Dear authors, 
I was curious about whether you have tried running the scripts with 13B.
I'm using 4x80GB A100, and it gives me OOM for train_generator.sh - and changing the batch size didn't particularly work for me 😢 

In case of you have succeeded, could you kindly share the code for 13B?

**Comment by OakYU** [comment]
you can try zero2_offload as the config

**Comment by hbin0701** [comment]
Thank you! :)
